### ISSUE TITLE
An error in the persistency thread stops everything

### ISSUE THREAD

**Issue by eigenein** [eigenein/my-iot-rs#43]
```
● my-iot.service - my-iot
   Loaded: loaded (/lib/systemd/system/my-iot.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-10-01 18:41:56 CEST; 5h 1min ago
 Main PID: 9236 (my-iot)
   Memory: 10.6M
   CGroup: /system.slice/my-iot.service
           └─9236 /home/pi/.cargo/bin/my-iot

Oct 01 22:05:36 raspberrypi my-iot[9236]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some("database disk image is malformed"))', src/libcore/result.rs:1084:5
Oct 01 22:05:36 raspberrypi my-iot[9236]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Oct 01 22:05:42 raspberrypi my-iot[9236]:  2019-10-01T22:05:42.363 INFO  my_iot::persistence          > nest::thermostat::…::ambient_temperature: Actual Celsius(22.5)
Oct 01 22:05:42 raspberrypi my-iot[9236]: thread 'my-iot::persistence' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1084:5
Oct 01 22:05:42 raspberrypi my-iot[9236]: thread 'my-iot::dispatcher' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1084:5
Oct 01 22:05:42 raspberrypi my-iot[9236]: thread 'my-iot::telegram::consumer::telegram' panicked at 'internal error: entered unreachable code', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/my-iot-0.24.0/src/services/telegram.rs:134:13
Oct 01 22:05:42 raspberrypi my-iot[9236]: thread 'my-iot::automator:automator' panicked at 'internal error: entered unreachable code', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/my-iot-0.24.0/src/services/automator.rs:54:9
Oct 01 22:06:02 raspberrypi my-iot[9236]: thread 'my-iot::nest:nest' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1084:5
Oct 01 22:06:02 raspberrypi my-iot[9236]: thread 'my-iot::db:db' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1084:5
Oct 01 22:06:33 raspberrypi my-iot[9236]: thread 'my-iot::buienradar:buienradar' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1084:5
```

**Comment by eigenein** [comment]
Fixed indirectly.
